### PR TITLE
Fix crash after restoration from seed

### PR DESCRIPTION
**Pull request by RyanRory**
This is very strange... But it fixed the crash...

### CODE REVIEW

**Comment by gmbnt** [comment]
What kind of message was failing to decrypt?

**Comment by RyanRory** [comment]
> What kind of message was failing to decrypt?

It was an unidentified sender message with a prekey bundle. The crash was happening on the logging. That was very strange to me...... After I changed the log function, everything seemed to be working well again.

**Comment by Mikunj** [comment]
What was the underlying error that it was printing? The `failDebug` was probably put there for a reason, maybe we can find out why it was erroring out ?

**Comment by RyanRory** [comment]
> What was the underlying error that it was printing? The `failDebug` was probably put there for a reason, maybe we can find out why it was erroring out ?

image

**Comment by Mikunj** [comment]
Hmm maybe investigate why it's throwing `No valid session`. What is the contents of the UD before decryption?

**Comment by RyanRory** [comment]
The situation was that during (or after) the restoration, I received 4 UD messages of which there are 2 whisper messages, a friend request message, and a prekey message. The friend request message was ignored. `No valid session` was thrown when decrypting these 2 whisper messages and the exception was `NoSessionException`. Thus there is an error message in that thread showing `No valid session`. The crash was happening after a failed decryption of the prekey message. The error was `SignalServiceKit.LokiSessionResetImplementation.Errors Code=0`.

**Comment by RyanRory** [comment]
Is it possible that the crash is because of the log flush? For other kinds of messages, `OWSFailDebug` will not run because the underlying error or exception has been handled before `OWSFailDebug`. And it looks like the main difference between `OWSFailDebug` and `OWSLogDebug` is for `OWSFailDebug`  there is a `Log flush`. And when the app was crash, it was stopping at the database write queue. So is it possible to be a database related issue?
image
image

**Comment by Mikunj** [comment]
`OWSFailDebug` is working as intended. Seems like the case you described is valid in why the app was crashing. I'm happy for this to be changed to `OWSLogDebug` instead.

Upon restoration, if we had messages on the swarm then we wouldn't be able decrypt them because our session doesn't exist

**Comment by gmbnt** [comment]
I think the conclusion is we don't really need to change anything 🙃

**Pull request closed without merging**
