### PR TITLE
Auto Generated Friend Request Bug Fixes

### PR DESCRIPTION
**Pull request by nielsandriesse**
This PR ensures that what we're doing is in line with the friend request protocol as outlined [here](https://github.com/loki-project/session-protocol-docs/wiki/Auto-Generated-Friend-Requests).

It also improves documentation.

### CODE REVIEW

**Comment by nielsandriesse** [comment]
For some reason contact sync message don't appear to be sent correctly. I'd like to fix that too in this PR.

**Comment by nielsandriesse** [comment]
Also, I'd like to hide the auto-generated friend request if it's auto-accepted in this PR

**Comment by Mikunj** [comment]
We should probably make a flag in data message or something

**Comment by nielsandriesse** [comment]
On second thought I feel like hiding auto-generated friend requests that are auto-accepted should be its own PR

**Pull request merged**
